; Generated by build tooling - CPU exception, hardware IRQ and yield stubs.
;
; The whole CPU state of an interrupted task ends up pushed on that task's
; own stack, so a context switch is just a matter of resuming on a
; different stack pointer. Both dispatchers therefore RETURN the stack to
; continue on, and the stubs load it with 'mov esp, eax'.
[BITS 32]
section .text
extern isr_handler
extern irq_handler
extern yield_handler

global isr0
global isr1
global isr2
global isr3
global isr4
global isr5
global isr6
global isr7
global isr8
global isr9
global isr10
global isr11
global isr12
global isr13
global isr14
global isr15
global isr16
global isr17
global isr18
global isr19
global isr20
global isr21
global isr22
global isr23
global isr24
global isr25
global isr26
global isr27
global isr28
global isr29
global isr30
global isr31
global irq0
global irq1
global irq2
global irq3
global irq4
global irq5
global irq6
global irq7
global irq8
global irq9
global irq10
global irq11
global irq12
global irq13
global irq14
global irq15
global yield_entry

isr0:
    cli
    push dword 0            ; dummy error code
    push dword 0
    jmp isr_common

isr1:
    cli
    push dword 0            ; dummy error code
    push dword 1
    jmp isr_common

isr2:
    cli
    push dword 0            ; dummy error code
    push dword 2
    jmp isr_common

isr3:
    cli
    push dword 0            ; dummy error code
    push dword 3
    jmp isr_common

isr4:
    cli
    push dword 0            ; dummy error code
    push dword 4
    jmp isr_common

isr5:
    cli
    push dword 0            ; dummy error code
    push dword 5
    jmp isr_common

isr6:
    cli
    push dword 0            ; dummy error code
    push dword 6
    jmp isr_common

isr7:
    cli
    push dword 0            ; dummy error code
    push dword 7
    jmp isr_common

isr8:
    cli
    push dword 8
    jmp isr_common

isr9:
    cli
    push dword 0            ; dummy error code
    push dword 9
    jmp isr_common

isr10:
    cli
    push dword 10
    jmp isr_common

isr11:
    cli
    push dword 11
    jmp isr_common

isr12:
    cli
    push dword 12
    jmp isr_common

isr13:
    cli
    push dword 13
    jmp isr_common

isr14:
    cli
    push dword 14
    jmp isr_common

isr15:
    cli
    push dword 0            ; dummy error code
    push dword 15
    jmp isr_common

isr16:
    cli
    push dword 0            ; dummy error code
    push dword 16
    jmp isr_common

isr17:
    cli
    push dword 17
    jmp isr_common

isr18:
    cli
    push dword 0            ; dummy error code
    push dword 18
    jmp isr_common

isr19:
    cli
    push dword 0            ; dummy error code
    push dword 19
    jmp isr_common

isr20:
    cli
    push dword 0            ; dummy error code
    push dword 20
    jmp isr_common

isr21:
    cli
    push dword 21
    jmp isr_common

isr22:
    cli
    push dword 0            ; dummy error code
    push dword 22
    jmp isr_common

isr23:
    cli
    push dword 0            ; dummy error code
    push dword 23
    jmp isr_common

isr24:
    cli
    push dword 0            ; dummy error code
    push dword 24
    jmp isr_common

isr25:
    cli
    push dword 0            ; dummy error code
    push dword 25
    jmp isr_common

isr26:
    cli
    push dword 0            ; dummy error code
    push dword 26
    jmp isr_common

isr27:
    cli
    push dword 0            ; dummy error code
    push dword 27
    jmp isr_common

isr28:
    cli
    push dword 0            ; dummy error code
    push dword 28
    jmp isr_common

isr29:
    cli
    push dword 0            ; dummy error code
    push dword 29
    jmp isr_common

isr30:
    cli
    push dword 0            ; dummy error code
    push dword 30
    jmp isr_common

isr31:
    cli
    push dword 0            ; dummy error code
    push dword 31
    jmp isr_common

irq0:
    cli
    push dword 0
    push dword 32
    jmp irq_common

irq1:
    cli
    push dword 0
    push dword 33
    jmp irq_common

irq2:
    cli
    push dword 0
    push dword 34
    jmp irq_common

irq3:
    cli
    push dword 0
    push dword 35
    jmp irq_common

irq4:
    cli
    push dword 0
    push dword 36
    jmp irq_common

irq5:
    cli
    push dword 0
    push dword 37
    jmp irq_common

irq6:
    cli
    push dword 0
    push dword 38
    jmp irq_common

irq7:
    cli
    push dword 0
    push dword 39
    jmp irq_common

irq8:
    cli
    push dword 0
    push dword 40
    jmp irq_common

irq9:
    cli
    push dword 0
    push dword 41
    jmp irq_common

irq10:
    cli
    push dword 0
    push dword 42
    jmp irq_common

irq11:
    cli
    push dword 0
    push dword 43
    jmp irq_common

irq12:
    cli
    push dword 0
    push dword 44
    jmp irq_common

irq13:
    cli
    push dword 0
    push dword 45
    jmp irq_common

irq14:
    cli
    push dword 0
    push dword 46
    jmp irq_common

irq15:
    cli
    push dword 0
    push dword 47
    jmp irq_common

; Software interrupt 0x30: a task asking to be rescheduled right now.
; No EOI here - no PIC was involved.
yield_entry:
    cli
    push dword 0
    push dword 48
    jmp yield_common


; Saves the segment registers and general purpose registers, switches to the
; kernel data segment, and hands %1 a pointer to the resulting frame.
%macro ENTER_HANDLER 0
    pusha                           ; edi esi ebp esp ebx edx ecx eax
    mov     ax, ds
    push    eax                     ; save the caller's data segment
    mov     ax, 0x10
    mov     ds, ax
    mov     es, ax
    mov     fs, ax
    mov     gs, ax
    push    esp                     ; registers_t *
%endmacro

; The handler returned the stack to resume on in eax. Loading it also discards
; the pointer argument pushed above.
%macro LEAVE_HANDLER 0
    mov     esp, eax
    pop     eax
    mov     ds, ax
    mov     es, ax
    mov     fs, ax
    mov     gs, ax
    popa
    add     esp, 8                  ; drop int_no and err_code
    iret
%endmacro

isr_common:
    ENTER_HANDLER
    call    isr_handler
    LEAVE_HANDLER

irq_common:
    ENTER_HANDLER
    call    irq_handler
    LEAVE_HANDLER

yield_common:
    ENTER_HANDLER
    call    yield_handler
    LEAVE_HANDLER
